baseurl = "http://localhost:1313/"
languageCode = "zh-cn"
uglyurls = true
relativeURLs = false
title = "Go学习资源"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
preserveTaxonomyNames = true
disablePathToLower = true

# Enable Google Analytics by entering your tracking id
#googleAnalytics = "c7442f5794ea2abb71c6ff05dc0b8779"

[params]
# General information
    author = "Ryan"
    keywords = "Go,Docker,Kubernetes,学习笔记"
    description = "Go学习笔记。"
    copyright = "版权所有，转载请注明出处"
    
    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/ruanzz/GoGoGo"
    
    version = ""
    logo = "images/logo.png"
    favicon = ""
    
    permalink = "#"
    
    # reward button, comment this to disable it
    reward = true
    
    # Custom assets
    custom_css = []
    custom_js  = []
    
    # Syntax highlighting theme
    highlight_css  = ""
    
    [params.palette]
    	primary = "red"
    	accent  = "teal"
    
    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "ruanzz"
	email   = "rzz1995@live.com"

[[menu.main]]
	name   = "前言"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Go"
	identifier = "go"
	url    = "/go/"
	weight = 100

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
